package mcp

func toolDefinitions() []map[string]any {
	return []map[string]any{
		tool("memory.open_project", "Create or open a project memory namespace.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":        map[string]any{"type": "string"},
				"repo_ref":          map[string]any{"type": "string"},
				"language":          map[string]any{"type": "string"},
				"default_branch_id": map[string]any{"type": "string"},
				"metadata":          map[string]any{"type": "object"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.append_event", "Append an immutable event to a project branch timeline.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":     map[string]any{"type": "string"},
				"session_id":     map[string]any{"type": "string"},
				"task_id":        map[string]any{"type": "string"},
				"branch_id":      map[string]any{"type": "string"},
				"type":           map[string]any{"type": "string"},
				"payload":        map[string]any{"type": "object"},
				"causation_id":   map[string]any{"type": "string"},
				"correlation_id": map[string]any{"type": "string"},
			},
			"required": []string{"project_id", "type"},
		}),
		tool("memory.record_command", "Record a command.executed event with a standard payload shape.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":     map[string]any{"type": "string"},
				"command":        map[string]any{"type": "string"},
				"branch_id":      map[string]any{"type": "string"},
				"session_id":     map[string]any{"type": "string"},
				"task_id":        map[string]any{"type": "string"},
				"exit_code":      map[string]any{"type": "integer"},
				"duration_ms":    map[string]any{"type": "integer"},
				"stdout_summary": map[string]any{"type": "string"},
				"stderr_summary": map[string]any{"type": "string"},
				"causation_id":   map[string]any{"type": "string"},
				"correlation_id": map[string]any{"type": "string"},
				"metadata":       map[string]any{"type": "object"},
			},
			"required": []string{"project_id", "command"},
		}),
		tool("memory.record_observation", "Record an observation.recorded event with a standard payload shape.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":     map[string]any{"type": "string"},
				"summary":        map[string]any{"type": "string"},
				"branch_id":      map[string]any{"type": "string"},
				"session_id":     map[string]any{"type": "string"},
				"task_id":        map[string]any{"type": "string"},
				"kind":           map[string]any{"type": "string"},
				"confidence":     map[string]any{"type": "number"},
				"evidence":       map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"related_files":  map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"causation_id":   map[string]any{"type": "string"},
				"correlation_id": map[string]any{"type": "string"},
				"metadata":       map[string]any{"type": "object"},
			},
			"required": []string{"project_id", "summary"},
		}),
		tool("memory.record_decision", "Record a decision.made event with a standard payload shape.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":       map[string]any{"type": "string"},
				"summary":          map[string]any{"type": "string"},
				"branch_id":        map[string]any{"type": "string"},
				"session_id":       map[string]any{"type": "string"},
				"task_id":          map[string]any{"type": "string"},
				"rationale":        map[string]any{"type": "string"},
				"alternatives":     map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"expected_outcome": map[string]any{"type": "string"},
				"confidence":       map[string]any{"type": "number"},
				"causation_id":     map[string]any{"type": "string"},
				"correlation_id":   map[string]any{"type": "string"},
				"metadata":         map[string]any{"type": "object"},
			},
			"required": []string{"project_id", "summary"},
		}),
		tool("memory.trace_decision", "Trace a decision back through related prior events and supporting facts.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":        map[string]any{"type": "string"},
				"decision_event_id": map[string]any{"type": "string"},
				"branch_id":         map[string]any{"type": "string"},
				"session_id":        map[string]any{"type": "string"},
				"task_id":           map[string]any{"type": "string"},
				"limit":             map[string]any{"type": "integer"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.record_plan", "Record a plan.created event with a standard payload shape.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":     map[string]any{"type": "string"},
				"summary":        map[string]any{"type": "string"},
				"steps":          map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"status":         map[string]any{"type": "string"},
				"branch_id":      map[string]any{"type": "string"},
				"session_id":     map[string]any{"type": "string"},
				"task_id":        map[string]any{"type": "string"},
				"causation_id":   map[string]any{"type": "string"},
				"correlation_id": map[string]any{"type": "string"},
				"metadata":       map[string]any{"type": "object"},
			},
			"required": []string{"project_id", "summary"},
		}),
		tool("memory.update_plan", "Record a plan.updated event with a standard payload shape.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":     map[string]any{"type": "string"},
				"summary":        map[string]any{"type": "string"},
				"steps":          map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"status":         map[string]any{"type": "string"},
				"branch_id":      map[string]any{"type": "string"},
				"session_id":     map[string]any{"type": "string"},
				"task_id":        map[string]any{"type": "string"},
				"causation_id":   map[string]any{"type": "string"},
				"correlation_id": map[string]any{"type": "string"},
				"metadata":       map[string]any{"type": "object"},
			},
			"required": []string{"project_id", "summary"},
		}),
		tool("memory.get_state", "Read a materialized state value.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"scope":      map[string]any{"type": "string"},
				"scope_id":   map[string]any{"type": "string"},
				"field":      map[string]any{"type": "string"},
				"branch_id":  map[string]any{"type": "string"},
			},
			"required": []string{"project_id", "scope", "scope_id", "field"},
		}),
		tool("memory.set_state", "Write a materialized state value.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"key": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"project_id": map[string]any{"type": "string"},
						"scope":      map[string]any{"type": "string"},
						"scope_id":   map[string]any{"type": "string"},
						"field":      map[string]any{"type": "string"},
						"branch_id":  map[string]any{"type": "string"},
					},
					"required": []string{"project_id", "scope", "scope_id", "field"},
				},
				"value": map[string]any{},
			},
			"required": []string{"key", "value"},
		}),
		tool("memory.list_facts", "List stable facts for a scope or branch.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":    map[string]any{"type": "string"},
				"scope":         map[string]any{"type": "string"},
				"scope_id":      map[string]any{"type": "string"},
				"subject":       map[string]any{"type": "string"},
				"predicate":     map[string]any{"type": "string"},
				"branch_id":     map[string]any{"type": "string"},
				"after_fact_id": map[string]any{"type": "string"},
				"limit":         map[string]any{"type": "integer"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.promote_fact", "Promote a stable fact into durable memory.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":    map[string]any{"type": "string"},
				"scope":         map[string]any{"type": "string"},
				"scope_id":      map[string]any{"type": "string"},
				"subject":       map[string]any{"type": "string"},
				"predicate":     map[string]any{"type": "string"},
				"value":         map[string]any{},
				"confidence":    map[string]any{"type": "number"},
				"evidence_refs": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"source_branch": map[string]any{"type": "string"},
			},
			"required": []string{"project_id", "scope", "scope_id", "subject", "predicate", "value"},
		}),
		tool("memory.promote_fact_from_events", "Promote a fact with explicit supporting event evidence.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":         map[string]any{"type": "string"},
				"scope":              map[string]any{"type": "string"},
				"scope_id":           map[string]any{"type": "string"},
				"subject":            map[string]any{"type": "string"},
				"predicate":          map[string]any{"type": "string"},
				"value":              map[string]any{},
				"confidence":         map[string]any{"type": "number"},
				"evidence_event_ids": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"source_branch":      map[string]any{"type": "string"},
			},
			"required": []string{"project_id", "scope", "scope_id", "subject", "predicate", "value", "evidence_event_ids"},
		}),
		tool("memory.branch_create", "Create a branch from a branch head or checkpoint.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":         map[string]any{"type": "string"},
				"from":               map[string]any{"type": "string"},
				"name":               map[string]any{"type": "string"},
				"from_checkpoint_id": map[string]any{"type": "string"},
			},
			"required": []string{"project_id", "from", "name"},
		}),
		tool("memory.branch_summary", "Summarize a branch with recent events and fact counts.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"branch_id":  map[string]any{"type": "string"},
				"limit":      map[string]any{"type": "integer"},
			},
			"required": []string{"project_id", "branch_id"},
		}),
		tool("memory.branch_compare", "Compare divergent events and facts between two branches.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":      map[string]any{"type": "string"},
				"left_branch_id":  map[string]any{"type": "string"},
				"right_branch_id": map[string]any{"type": "string"},
			},
			"required": []string{"project_id", "left_branch_id", "right_branch_id"},
		}),
		tool("memory.branch_diff_summary", "Summarize the differences between two branches.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":      map[string]any{"type": "string"},
				"left_branch_id":  map[string]any{"type": "string"},
				"right_branch_id": map[string]any{"type": "string"},
				"limit":           map[string]any{"type": "integer"},
			},
			"required": []string{"project_id", "left_branch_id", "right_branch_id"},
		}),
		tool("memory.branch_adopt", "Mark a branch as the canonical default branch for a project.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"branch_id":  map[string]any{"type": "string"},
			},
			"required": []string{"project_id", "branch_id"},
		}),
		tool("memory.adopt_branch_with_reason", "Adopt a branch and append a branch.adopted event with rationale.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":     map[string]any{"type": "string"},
				"branch_id":      map[string]any{"type": "string"},
				"reason":         map[string]any{"type": "string"},
				"summary":        map[string]any{"type": "string"},
				"session_id":     map[string]any{"type": "string"},
				"task_id":        map[string]any{"type": "string"},
				"correlation_id": map[string]any{"type": "string"},
				"causation_id":   map[string]any{"type": "string"},
				"metadata":       map[string]any{"type": "object"},
			},
			"required": []string{"project_id", "branch_id", "reason"},
		}),
		tool("memory.timeline_query", "Query events by project, branch, task, session, or type.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":       map[string]any{"type": "string"},
				"branch_id":        map[string]any{"type": "string"},
				"task_id":          map[string]any{"type": "string"},
				"session_id":       map[string]any{"type": "string"},
				"type":             map[string]any{"type": "string"},
				"after_logical_ts": map[string]any{"type": "string"},
				"since":            map[string]any{"type": "string", "format": "date-time"},
				"until":            map[string]any{"type": "string", "format": "date-time"},
				"limit":            map[string]any{"type": "integer"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.recent_context", "Return a compact recent-event view with a lightweight summary.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"branch_id":  map[string]any{"type": "string"},
				"task_id":    map[string]any{"type": "string"},
				"session_id": map[string]any{"type": "string"},
				"type":       map[string]any{"type": "string"},
				"since":      map[string]any{"type": "string", "format": "date-time"},
				"until":      map[string]any{"type": "string", "format": "date-time"},
				"limit":      map[string]any{"type": "integer"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.task_snapshot", "Return an integrated snapshot for a task or session including branch, events, facts, state, and latest decision context.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":   map[string]any{"type": "string"},
				"task_id":      map[string]any{"type": "string"},
				"session_id":   map[string]any{"type": "string"},
				"branch_id":    map[string]any{"type": "string"},
				"state_fields": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"limit":        map[string]any{"type": "integer"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.session_snapshot", "Return an integrated snapshot for a session including branch, events, facts, state, and latest decision context.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id":   map[string]any{"type": "string"},
				"session_id":   map[string]any{"type": "string"},
				"branch_id":    map[string]any{"type": "string"},
				"state_fields": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"limit":        map[string]any{"type": "integer"},
			},
			"required": []string{"project_id", "session_id"},
		}),
		tool("memory.project_snapshot", "Return an integrated snapshot for a project including default branch, recent events, facts, and summary context.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"branch_id":  map[string]any{"type": "string"},
				"limit":      map[string]any{"type": "integer"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.fact_summary", "Return a compact fact view with lightweight grouping summaries.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"scope":      map[string]any{"type": "string"},
				"scope_id":   map[string]any{"type": "string"},
				"subject":    map[string]any{"type": "string"},
				"predicate":  map[string]any{"type": "string"},
				"branch_id":  map[string]any{"type": "string"},
				"limit":      map[string]any{"type": "integer"},
			},
			"required": []string{"project_id"},
		}),
		tool("memory.checkpoint", "Create a checkpoint marker for the current branch head.", map[string]any{
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"branch_id":  map[string]any{"type": "string"},
				"metadata":   map[string]any{"type": "object"},
			},
			"required": []string{"project_id", "branch_id"},
		}),
	}
}

func tool(name, description string, schema map[string]any) map[string]any {
	return map[string]any{
		"name":        name,
		"description": description,
		"inputSchema": schema,
	}
}
